# permissions for end users to view cacheregions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cacheregion-viewer-role
rules:
- apiGroups:
  - engytita.org
  resources:
  - cacheregions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - engytita.org
  resources:
  - cacheregions/status
  verbs:
  - get
