name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unit Tests
        run: make test

      - name: Check for unstaged changes
        run: git diff --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Operator SDK
        run: |
          curl -L https://github.com/operator-framework/operator-sdk/releases/download/v1.21.0/operator-sdk_linux_amd64 -o operator-sdk
          chmod +x operator-sdk
          sudo mv operator-sdk /bin/

      - name: Install Kind
        run: go install sigs.k8s.io/kind@v0.14.0

      - name: Create Kind Cluster
        run: ./hack/kind.sh

      - name: Build and Deploy Operator with Skaffold
        uses: hiberbee/github-action-skaffold@1.18.0
        with:
          command: run

      - name: E2E Integration tests
        run: make test-e2e
